## Title

# Synopsis:

# Data Processing 

```{r, cache=TRUE}
data <- read.csv("repdata-data-StormData.csv")
```

# Results

**Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?**

```{r}
data$HEALTH_EFFECTS <- data$INJURIES + data$FATALITIES
health <- aggregate(data$HEALTH_EFFECTS, by=list(data$EVTYPE), FUN=sum)
health <- health[sort.list(health$x, decreasing=TRUE),]
names(health) <- c("event", "count")
```
```{r echo=FALSE}
n <- 5
```
Top `r n` most harmful weather event types:

```{r echo=FALSE}
colors <- c("blue", "green", "red", "orange", "violet")

p <- head(health, n=n)
barplot(p$count, col=colors, xlab="Event Type", ylab="Injuries + Deaths", main="Most Harmful Weather Events")
legend("topright", legend=p$event, fill=colors)

```

**Across the United States, which types of events have the greatest economic consequences?**

```{r}
get_cost <- function(cost, modifier) {
    mult <- 0

    if(modifier == "K") {
        mult <- 1000
    }

    if(modifier == "M") {
        mult <- 1000000
    }

    if(modifier == "B") {
        mult <- 1000000000 
    }

    cost * mult
}

cost <- data.frame(EVTYPE=data$EVTYPE, PROPDMG=data$PROPDMG, PROPDMGEXP=data$PROPDMGEXP, CROPDMG=data$CROPDMG, CROPDMGEXP=data$CROPDMGEXP)
x <- mapply(get_cost, cost$PROPDMG, cost$PROPDMGEXP) 
y <- mapply(get_cost, cost$CROPDMG, cost$CROPDMGEXP) 
cost$total_cost <- (x + y) / 1000
z <- aggregate(cost$total_cost, by=list(cost$EVTYPE), FUN=sum)
z <- z[sort.list(z$x, decreasing=TRUE),]
names(z) <- c("event", "count") 
```

Most costly weather events:

```{r}
p <- head(z, n=n)
barplot(p$count, col=colors, xlab="Event Type", ylab="Cost (K Dollars)", main="Most Expensive Weather Events")
legend("topright", legend=p$event, fill=colors)
```


